import { NextRequest, NextResponse } from 'next/server';
import { daemonService } from '../daemon-service';

export async function GET(request: NextRequest) {
  try {
    // Get system injections from the daemon
    const injections = await daemonService.getSystemInjections();
    
    // Filter for system_injection type only
    const systemInjections = injections.filter(injection => 
      injection.type === 'system_injection'
    );

    console.log(`💉 [SystemInjection] Providing ${systemInjections.length} system injections`);

    return NextResponse.json({
      success: true,
      injections: systemInjections,
      count: systemInjections.length
    });

  } catch (error) {
    console.error('💉 [SystemInjection] Error getting system injections:', error);
    return NextResponse.json(
      { error: 'Failed to get system injections' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  // This endpoint could be used for manual system injection testing
  try {
    const body = await request.json();
    const { promptDelta, validUntil } = body;

    if (!promptDelta) {
      return NextResponse.json(
        { error: 'Missing promptDelta field' },
        { status: 400 }
      );
    }

    // For testing purposes - this would typically be generated by the daemon
    console.log(`💉 [SystemInjection] Manual injection: ${promptDelta.substring(0, 50)}...`);

    return NextResponse.json({
      success: true,
      message: 'Manual system injection received',
      promptDelta,
      validUntil: validUntil || Date.now() + (10 * 60 * 1000)
    });

  } catch (error) {
    console.error('💉 [SystemInjection] Error processing manual injection:', error);
    return NextResponse.json(
      { error: 'Failed to process manual injection' },
      { status: 500 }
    );
  }
}